
@startuml
!include <c4/C4_Component.puml>

'ref http://plantuml.com/stdlib

LAYOUT_WITH_LEGEND()

title Covid Modelling Model Runner Components

Container(ui, "Web Interface", "Azure", "Allows policy makers to schedule simulations and compare what different models predict")
ContainerDb(queue, "Job Queue", "GitHub")
Container_Boundary(model_runner, "Model Runner") {
  Component_Ext(job_runner, "Actions Runner", "Azure: VM", "Fetches and executes jobs from GitHub Actions")
  Component_Ext(docker, "Docker Engine", "Azure: VM", "Manages Docker Containers")
  Component(runner, "Model Runner", "Azure: VM (Docker Container)", "Spawns other containers to execute simulation")
  Component(model, "Model Connector", "Azure: VM (Docker Container)", "Converts parameters to model-specific parameters, and executes simulation")
}
Container_Ext(packages, "Container Repository", "GitHub: Packages", "Stores model code")

System_Ext(models, "Models", "COVID-19 model codes")

Rel_Left(job_runner, queue, "Fetches jobs")
Rel(job_runner, docker, "Creates model runner")
Rel(docker, packages, "Fetches container images")
Rel(docker, runner, "Executes")
Rel(runner, docker, "Creates model connectors")
Rel(docker, model, "Executes")
Rel(runner, ui, "Updates simulation results")
Rel(packages, models, "Incorporates")
@enduml
