@startuml
!include <c4/C4_Component.puml>

'ref http://plantuml.com/stdlib

LAYOUT_WITH_LEGEND()

title Covid Modelling Interface Components

Person_Ext(policy_maker, "Policy Maker" , "A non-expert user" )

Container_Boundary(ui, "Web Interface") {
  Component(web, "Web Application", "Azure: Container Instance (JavaScript, Next.js)", "Allows policy makers to schedule simulations and compare what different models predict")
  Component(db, "Database", "Azure: MySQL", "Details of simulations")
  Component(blobs, "Object Store", "Azure: Blob Storage", "Results of simulations")
  Component_Ext(auth, "Login", "GitHub: OAuth", "Authenticates users")
}
ContainerDb(queue, "Job Queue", "GitHub")
Container(model_runner, "Model Runner", "GitHub, Azure", "Interprets parameters and executes simulations")

Rel_Down(policy_maker, auth, "Authenticates")
Rel_Right(policy_maker, web, "Sets up simulation")
Rel_Down(web, auth, "Checks token")
Rel(web, queue, "Schedules simulation")
Rel(web, db, "Updates and queries")
Rel(web, blobs, "Updates and queries")
Rel_Left(model_runner, web, "Updates simulation results")
@enduml
