
@startuml
!include <c4/C4_Context.puml>

'ref http://plantuml.com/stdlib

LAYOUT_WITH_LEGEND()

title Covid Modelling System Context

Person_Ext(policy_maker, "Policy Maker" , "A non-expert user" )
Person_Ext(modeller, "Modeller" , "A model developer" )

System(covid_modelling, "Covid Modelling", "Allows policy makers to schedule simulations and compare what different models predict")

System_Ext(models, "Models", "COVID-19 model codes")

Rel(policy_maker, covid_modelling, "Runs models")
Rel(modeller, models, "Develops models")
Rel(covid_modelling, models, "Uses")
@enduml
